package org.ispcluj;

//TODO: REQ-1
public record TrainService(String id, int passengerCount, String lineCode) {
    // you can create a classic TrainService class and delete this if it's better for you
    // here you can add extra methods if needed (getters, setters, hashCode, equals are already generated by the record)
    //check if toString works without generating it, if not and you need it, generate it.

    public void validateRoute() {
        //check and throw RouteValidationException if needed from here
    }
}
